src/Entity/JobOffer.php
<?php

namespace App\Entity;

use App\Repository\JobOfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobOfferRepository::class)]
class JobOffer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 200)]
    private ?string $Title = null;

    #[ORM\Column(length: 100)]
    private ?string $Location = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Detailled_description = null;

    #[ORM\ManyToOne(inversedBy: 'jobOffers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Recrutor $recrutor = null;

    #[ORM\OneToMany(mappedBy: 'jobOffer', targetEntity: Candidature::class, orphanRemoval: true)]
    private Collection $candidatures;

    #[ORM\Column]
    private ?bool $validated = null;

    #[ORM\ManyToOne(inversedBy: 'jobOffers')]
    private ?Consultant $consultant = null;

    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->Location;
    }

    public function setLocation(string $Location): self
    {
        $this->Location = $Location;

        return $this;
    }

    public function getDetailledDescription(): ?string
    {
        return $this->Detailled_description;
    }

    public function setDetailledDescription(string $Detailled_description): self
    {
        $this->Detailled_description = $Detailled_description;

        return $this;
    }

    public function getRecrutor(): ?Recrutor
    {
        return $this->recrutor;
    }

    public function setRecrutor(?Recrutor $recrutor): self
    {
        $this->recrutor = $recrutor;

        return $this;
    }

    /**
     * @return Collection<int, Candidature>
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): self
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures->add($candidature);
            $candidature->setJobOffer($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): self
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getJobOffer() === $this) {
                $candidature->setJobOffer(null);
            }
        }

        return $this;
    }

    public function isValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): self
    {
        $this->validated = $validated;

        return $this;
    }

    public function getConsultant(): ?Consultant
    {
        return $this->consultant;
    }

    public function setConsultant(?Consultant $consultant): self
    {
        $this->consultant = $consultant;

        return $this;
    }
}

src/Entity/Recrutor.php
<?php

namespace App\Entity;

use App\Repository\RecrutorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecrutorRepository::class)]
class Recrutor
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private array $enterprise_address = [];

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $enterprise_name = null;

    #[ORM\OneToOne(inversedBy: 'recrutor', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'recrutor', targetEntity: JobOffer::class, orphanRemoval: true)]
    private Collection $jobOffers;

    public function __construct()
    {
        $this->jobOffers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEnterpriseAddress(): array
    {
        return $this->enterprise_address;
    }

    public function setEnterpriseAddress(?array $enterprise_address): self
    {
        $this->enterprise_address = $enterprise_address;

        return $this;
    }

    public function getEnterpriseName(): ?string
    {
        return $this->enterprise_name;
    }

    public function setEnterpriseName(?string $enterprise_name): self
    {
        $this->enterprise_name = $enterprise_name;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, JobOffer>
     */
    public function getJobOffers(): Collection
    {
        return $this->jobOffers;
    }

    public function addJobOffer(JobOffer $jobOffer): self
    {
        if (!$this->jobOffers->contains($jobOffer)) {
            $this->jobOffers->add($jobOffer);
            $jobOffer->setRecrutor($this);
        }

        return $this;
    }

    public function removeJobOffer(JobOffer $jobOffer): self
    {
        if ($this->jobOffers->removeElement($jobOffer)) {
            // set the owning side to null (unless already changed)
            if ($jobOffer->getRecrutor() === $this) {
                $jobOffer->setRecrutor(null);
            }
        }

        return $this;
    }
}

src/Form/RecrutorType.php
<?php

namespace App\Form;

use App\Entity\Recrutor;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecrutorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('enterprise_address')
            ->add('enterprise_name')
            ->add('saveRecrutor', SubmitType::class, ['label' => 'Enregistrer ce recruteur'])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recrutor::class,
        ]);
    }
}

src/Controller/RecrutorController.php
<?php

namespace App\Controller;

use App\Entity\Recrutor;
use App\Entity\User;
use App\Form\RecrutorType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RecrutorController extends AbstractController
{
    #[Route('/recrutor', name: 'app_recrutor')]
    public function index(): Response
    {
        return $this->render('recrutor/index.html.twig', [
            'controller_name' => 'RecrutorController',
        ]);
    }

    #[Route('/recrutor/creation-selection', name: 'app_recrutor_creation_selection')]
    public function create_selection(): Response
    {
        return $this->render('recrutor/create_selection.html.twig', [
            'controller_name' => 'CandidateController',
        ]);
    }

    #[Route('/recrutor/select-user', name: 'app_select_user_for_recrutor')]
    public function select_user(\Doctrine\Persistence\ManagerRegistry $doctrine): Response
    {
        $availableUser = $doctrine->getRepository(User::class)->findAll();
        return $this->render('recrutor/select_user_for_recrutor.html.twig', [
            'availableUser' => $availableUser,
        ]);
    }

    #[Route('/recrutor/select-user-for-recrutor-update', name: 'app_select_user_for_recrutor_update')]
    public function select_user_for_recrutor_update(\Doctrine\Persistence\ManagerRegistry $doctrine): Response
    {
        $availableUser = $doctrine->getRepository(User::class)->findAll();
        return $this->render('recrutor/select_user_for_recrutor_update.html.twig', [
            'availableUser' => $availableUser,
        ]);
    }

    #[Route('/recrutor/creation/{id}', name: 'app_recrutor_creation')]
    public function create_recrutor(Request $request,User $user, EntityManagerInterface $entityManager): Response
    {
        $recrutor = new Recrutor();
        $recrutor->setUser($user);
        $recrutor->getUser()->addRoles("ROLE_RECRUTOR");

        $form = $this->createForm(RecrutorType::class, $recrutor);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($recrutor);
            $entityManager->flush();
            // do anything else you need here, like send an email

            return $this->redirectToRoute('app_home');
        }

        return $this->render('recrutor/create_recrutor.html.twig', [
            'recrutorCreationForm' => $form->createView(),
        ]);
    }

    #[Route('/recrutor/update/{id}', name: 'app_recrutor_update')]
    public function create_candidate(Request $request,User $user, EntityManagerInterface $entityManager): Response
    {
        $recrutor = $user->getRecrutor();
        $form = $this->createForm(RecrutorType::class, $recrutor);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($recrutor);
            $entityManager->flush();
            // do anything else you need here, like send an email

            return $this->redirectToRoute('app_home');
        }

        return $this->render('recrutor/create_recrutor.html.twig', [
            'recrutorCreationForm' => $form->createView(),
        ]);
    }

    #[Route('/recrutor/{id}/display-offers', name: 'app_recrutor_display_offers')]
    public function recrutor_display_offers(Request $request,User $user, EntityManagerInterface $entityManager): Response
    {
        $recrutor = $user->getRecrutor();
        $jobOffers = $recrutor->getJobOffers();


        return $this->render('recrutor/recrutor_display_offers.html.twig', [
            'JobOffers' => $jobOffers,
        ]);
    }


}

templates/recrutor/create_recrutor.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création recruteur{% endblock %}

{% block body %}
    <h1>Création recruteur</h1>

    {{ form_start(recrutorCreationForm) }}

    {{ form_row(recrutorCreationForm.enterprise_name, {
        label: 'Nom de votre entreprise'
    }) }}

    {{ form_row(recrutorCreationForm.enterprise_address, {
        label: 'Adresse de votre entreprise'
    }) }}


    {{ form_end(recrutorCreationForm) }}
{% endblock %}

templates/recrutor/create_selection.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CandidateController!{% endblock %}

{% block body %}
    <div class="m-5 p-5">
        <h1>Make your choice </h1>


        <ul>
            <li><a href="{{ path('app_select_user_for_recrutor') }}">Créer un recruteur depuis un compte utilisateur existant</a></li>
            <li><a href="{{ path('app_register') }}">Créer un candidat avec un nouveau compte utilisateur</a></li>
        </ul>
    </div>
{% endblock %}

templates/recrutor/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecrutorController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/apps/my-nine-eval/my-nine-eval/src/Controller/RecrutorController.php'|file_link(0) }}">src/Controller/RecrutorController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/apps/my-nine-eval/my-nine-eval/templates/recrutor/select_user_for_consultant_creation.html.twig'|file_link(0) }}">templates/recrutor/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/recrutor/recrutor_display_offers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Offers from recrutor{% endblock %}

{% block body %}


    <div class="example-wrapper">
        <h1>Offers posted by you</h1>

        <div class="row">
            {% for jobOffer in JobOffers %}
                <div class="card m-2" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{ jobOffer.Title }}</li>
                        <li class="list-group-item">{{ jobOffer.Location }}</li>
                        <li class="list-group-item">{{ jobOffer.detailledDescription }}</li>
                        <li class="list-group-item"><a href="{{ path('app_candidature_display', {'id' : jobOffer.id}) }}">Consulter les candidatures à cette offre</a></li>

                    </ul>
                </div>

            {% endfor %}
        </div>

    </div>

    {{ include('partial/_retour_menu.html.twig') }}

{% endblock %}

templates/recrutor/select_user_for_recrutor.html.twig
{% extends 'base.html.twig' %}

{% block title %}User selection{% endblock %}

{% block body %}


    <div class="example-wrapper">
        <h1>User selection</h1>

        <ul>
            {% for user in availableUser %}
                {% if user.recrutor is same as (null) %}
                    <li>
                        {{ user.email }}
                        <a href="{{ path('app_recrutor_creation', {'id': user.id}) }}" class="btn btn-outline-success">Sélectionner</a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>

    </div>
{% endblock %}

templates/recrutor/select_user_for_recrutor_update.html.twig
{% extends 'base.html.twig' %}

{% block title %}User selection{% endblock %}

{% block body %}


<div class="example-wrapper">
    <h1>User selection</h1>

    <ul>
        {% for user in availableUser %}
            {% if user.recrutor is not null %}
        <li>
            {{ user.email }}
            <a href="{{ path('app_recrutor_update', {'id': user.id}) }}" class="btn btn-outline-success">Sélectionner</a>
        </li>
            {% endif %}
        {% endfor %}
    </ul>

</div>
{% endblock %}